LOG_FILE_PATH = "./log/mylog.log"
MAX_LOG_FILE_SIZE  =  52428800 #50 MB
MAX_LOG_FILE_BACKUP_COUNT = 250  # MAximum 25 files will be kept




DUMMY_START_NODE = "DUMMY_START_NODE"
DUMMY_END_NODE = "DUMMY_END_NODE"