IS_ACTION_ENTRIES_PER_TABLE_FIXED_SIZE = True
ENABLE_READ_MODIFY_WRITE_ACTION = False
PER_TABLE_ACTION_ENTRY_COUNT = 8192

MEMORY_BLOCK_COUNT_FOR_PACKING = 3


REGISTER_EXTERN_CATEGORY = ["RegisterReadExtern_8"]